sources:
  - type: golang
    path: go.mod
version: 1.0.11
excludes:
  # Releases are done with Release Droid because PK does not yet support release process for Go projects.
  - "E-PK-CORE-26: 'release_config.yml' exists but must not exist. Reason: Release-droid configuration is replaced by release.yml"
