sonar.projectKey=com.exasol:exasol-driver-go
sonar.organization=exasol
sonar.sources=.
sonar.exclusions=*_test.go,examples/**
sonar.tests=.
sonar.test.inclusions=*_test.go
sonar.go.coverage.reportPaths=./coverage.out
sonar.coverage.exclusions=**/*_test.go,**/*_mock.go,pkg/integrationTesting/**
# Ignore SQL Injection Risks in the integration tests
sonar.issue.ignore.multicriteria=ex1,ex2
sonar.issue.ignore.multicriteria.ex1.ruleKey=go:S2077
sonar.issue.ignore.multicriteria.ex1.resourceKey=itest/integration_test.go
# Ignore duplicated string literals in tests
sonar.issue.ignore.multicriteria.ex2.ruleKey=go:S1192
sonar.issue.ignore.multicriteria.ex2.resourceKey=**/*_test.go
